version: 2.1
orbs:
  node: circleci/node@1.1.6
  gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
workflows:
    build:
      jobs:
        - gke/publish-and-rollout-image:
            cluster: cluster-1
            container: graphql-app-5558d8c7f-rvc2v
            deployment: graphql-app
            image: graphql-app
            tag: $CIRCLE_SHA1