version: 2.1
orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - gcp-gke/install
      - gcp-gke/publish-and-rollout-image:
          cluster: cluster-1
          container: app
          deployment: graphql-app
          image: graphql-app
          tag: $CIRCLE_SHA1
workflows:
    build:
      jobs:
        - deploy