version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy:
    docker:
      - image: node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c5:bb:fd:1b:2d:31:f5:80:1d:25:b2:b7:f2:44:f3:b7"
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: export IMAGE_NAME=fullstack-react-graphql
      - run: export PORT=4000
      - run: export VM_IP=35.224.135.155
      - run: export TGT_IMAGE=$DOCKER_ID/$IMAGE_NAME:$IMAGETAG
      - run: echo $TGT_IMAGE
      - run: docker build -t $TGT_IMAGE
      - run: echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
      - run: docker push $TGT_IMAGE
      - run: ssh -o StrictHostKeyChecking=no $DOCKER_ID@$VM_IP "/bin/bash ~/deploy_docker.sh $TGT_IMAGE $IMAGE_NAME $PORT"

workflows:
    build:
      jobs:
        - deploy