version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-and-build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
            - run: npm run start:prod
workflows:
    test-and-build:
      jobs:
        - test-and-build