version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy:
    docker:
      - image: node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c5:bb:fd:1b:2d:31:f5:80:1d:25:b2:b7:f2:44:f3:b7"
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Setup Env
          command: |
            echo 'export IMAGE_NAME=fullstack-react-graphql' >> $BASH_ENV
            echo 'export PORT=4000' >> $BASH_ENV
            echo 'export VM_IP=35.224.135.155' >> $BASH_ENV
            echo 'export TGT_IMAGE=$DOCKER_ID/$IMAGE_NAME:${CIRCLE_SHA1}' >> $BASH_ENV
            source $BASH_ENV 
      - run:
          name: Docker Build and Push
          command: |
            docker build -t $TGT_IMAGE
            echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
            docker push $TGT_IMAGE
      - run:
          name: Deploy to F1 Micro VM
          command: |
            ssh -o StrictHostKeyChecking=no $DOCKER_ID@$VM_IP "/bin/bash ~/deploy_docker.sh $TGT_IMAGE $IMAGE_NAME $PORT"

workflows:
    build:
      jobs:
        - deploy