version: 2.1
orbs:
  node: circleci/node@1.1.6
  gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
jobs:
  deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: export IMAGE_NAME=fullstack-react-graphql
      - run: export PORT=4000
      - run: export VM_IP=35.224.135.155
      - run: export TGT_IMAGE=$DOCKER_ID/$IMAGE_NAME:$TAG
      - run: docker build -t $TGT_IMAGE
      - run: echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
      - run: docker push $TGT_IMAGE
      - run: ssh -o StrictHostKeyChecking=no $DOCKER_ID@$VM_IP "/bin/bash ~/deploy_docker.sh $TGT_IMAGE $IMAGE_NAME $PORT"

workflows:
    build:
      jobs:
        - deploy